version: '3.8'
services:
  api1: &api1 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - postgres
    networks:
      - mynetwork

  api2:
    <<: *api1
    ports:
    - "3002:8080"

  redis:
    image: redis:alpine
    networks:
      - mynetwork

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - mynetwork

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - mynetwork


volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
